Fix SELinuxHostTest#testNetdDomain failure
netd exec()s various iptables commands. Make sure they're allowed so we
don't have CTS failures.

Fixes:

Stack Trace:
=========
junit.framework.AssertionFailedError: Expected 1 process in SELinux
domain "u:r:netd:s0" Found "[label: u:r:netd:s0 user: root pid: 594
ppid: 1 cmd: /system/bin/netd, label: u:r:netd:s0 user: root pid: 968
ppid: 594 cmd: /system/bin/iptables-restore, label: u:r:netd:s0 user:
root pid: 969 ppid: 594 cmd: /system/bin/ip6tables-restore]"
expected:<1> but was:<3>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at junit.framework.Assert.assertEquals(Assert.java:78)
        at junit.framework.Assert.assertEquals(Assert.java:234)
        at junit.framework.TestCase.assertEquals(TestCase.java:401)
        at android.security.cts.SELinuxHostTest.assertDomainOne(SELinuxHostTest.java:544)
        at android.security.cts.SELinuxHostTest.testNetdDomain(SELinuxHostTest.java:700)

Bug: 34721525
Test: CTS compiles
Change-Id: I2b418affe21e1c6e3f64778fbf0e3b02f95472a6

Former-commit-id: fe443b2180a7171410c74493af80aeae18b5f304