Fix PixelCopyTests testNotLeaking
Symptom:
PixCopyTestsPixelCopyTests#testNotLeaking fail:
java.lang.AssertionError: Memory leaked.

Root cause:
The test case is not very reasonable since garbage collection is not
guaranteed  to run in time after pixel copy.

Solution:
1.call system.gc() explicitly in each iteration and
2.enlarge the memory difference tolerance before and after pixel copy
from 1000 to 2000.

Change-Id: Ia521a8b8fd35ed82fe63c27d5751cb982d013485

Former-commit-id: 08d9d605dbab8dd99951dd7a60815dba61d368cc